### ISSUE TITLE
Price Breaks

### ISSUE THREAD

**Issue by skornev** [mike182uk/cart#12]
At this moment  the only way to ignore keys in the hashing process is to add elements to ignoreKeys array.
        $ignoreKeys = array('quantity', 'price');

Is there any more elegant way to deal with price breaks?

**Comment by mike182uk** [comment]
Hey, im not sure what you mean by price breaks. Can you give me an example?

**Comment by skornev** [comment]
Hi,
That's volume discounts ( a reduction in price, esp for bulk purchase).
Here are few examples
https://d3sg2ldiig8y1n.cloudfront.net/sites/default/files/uploads/images/Price_breaks.png
http://www.digikey.com/product-detail/en/LM2931AD33R/497-6880-1-ND/1880259
On the first picture it shows that if you buy just a pair of gloves you pay 35.99 pounds but if you want to buy, for instance, 6 pairs you ll get a 1 pound discount for each pair. 

Thanks.

**Comment by mike182uk** [comment]
Currently there is not a way of doing this without modifying the cart. I would be hesitant to adding this type of logic to the cart class itself and would instead opt use a collaborator to handle this:

```php
$priceBreakDiscount = new PriceBreakDiscount('<sku>', '<quantity>', '<new price>');
$discountCalculator = new DiscountCalculator($cart);

$discountCalculator->addDiscount($priceBreakDiscount);

$discountTotal = $discountCalculator->getDiscountTotal();

$discountedCartTotal = $cart->total() - $discountTotal;
```

**Comment by skornev** [comment]
To my opinion the solution you have suggested it's more to deal with promo code discounts. 
Anyway, I still think that there should be  a way to change $ignoreKeys to manage hashing process. 

Thanks.
