### ISSUE TITLE
Error in call

### ISSUE THREAD

**Issue by mrsnax** [mike182uk/cart#17]
Hi,

Im using this library has error when im calling Cart;

Warning: The use statement with non-compound name 'Cart' has no effect

Fatal error: Class 'Cart' not found

Any Soliutions?

**Comment by mike182uk** [comment]
Hey, can you provide an example oh how you are using this and where the error is occurring?

**Comment by isaac-perkins** [comment]
I've got the same issue just now. Cart not found, I'll keep digging...

require_once('../../vendor/autoload.php');

use Cart;
use Cart\Storage\SessionStore;

$id = 'cart' . date('Y-m-d');

$cartSessionStore = new SessionStore();

$this->cart = new Cart($id, $cartSessionStore);

**Comment by isaac-perkins** [comment]
nope, too long (looking), sorry....got to get this job done...

**Comment by mike182uk** [comment]
@mrsnax @isaac-perkins I had a typo in the example in the README. It should of been:

```php
use Cart\Cart;
use Cart\Storage\SessionStore;

$id = 'cart-01';
$cartSessionStore = new SessionStore();

$cart = new Cart($id, $cartSessionStore);
```

The important bit being `use Cart\Cart;` instead of `use Cart;`

I've updated the README.
