### ISSUE TITLE
cart is cleared on page close

### ISSUE THREAD

**Issue by hycday** [mike182uk/cart#20]
I am adding items to the cart, it is saving the state perfectly but then when page is closed, then reopened, cart is empty, how to keep the cart in session ?

**Comment by mike182uk** [comment]
Hey @hycday,

When you initialise the cart, straight afterwards you will want to call the [restore](https://github.com/mike182uk/cart#save--restore-cart-state) method to re-populate the cart from a saved state.

**Comment by hycday** [comment]
it is working when I refresh the page, or link to another page calling the cart/restoring it, but if I close the browser, cart is lost

**Comment by mike182uk** [comment]
@hycday This will be down to how you have PHP sessions configured for your web server. Unfortunately you will have to refer to the PHP docs to see how you can change this behaviour.

Alternatively you could try using the cookie storage driver, or implementing your own [storage driver](https://github.com/mike182uk/cart#cart-storage-implementation).
