### ISSUE TITLE
$cart->update() for an item option

### ISSUE THREAD

**Issue by grubbychicken** [mike182uk/cart#21]
Hi @mike182uk

Thanks for the great cart, it's exactly what I need! Although, I have a question:

Is it possible to update an item option currently?

for example, say I have the following:

```php
$itemData = [
        'name' => $name,
        'sku' => $sku,
        'price' => $price,
        'tax' => 200,
        'options' => [
                'brand' => $brand,
                'picture_uri' => $picture_uri,
         ]
];

$item =  new CartItem($itemData);
$Cart->add($item);
$Cart->save();
```

And I then want to update the brand for example:

```php
$Cart->update($id, ['options']['brand'], $newBrand);
```

This obviously doesn't work and throws an error.  But is it possible to do something like this?

**Comment by mike182uk** [comment]
Hey @grubbychicken,

Unfortunately `update` only works with single keys at the moment. If you wanted to update a nested key, you would need to update the whole of the parent array, something like:

```php
$item = $cart->get($itemId);

$cart->update($itemId, 'options', array_merge($item->options, ['brand' => $newBrand]));
```
